In [1]:
import gymnasium as gym
import numpy as np
import matplotlib.pyplot as plt


In [2]:
# -------------------------------------------------
# Create FrozenLake Environment
# -------------------------------------------------
env_desc = [
      "SFFF",
      "FFHF",
       "FHFF",
       "FFFG"
]

env = gym.make("FrozenLake-v1", desc=env_desc, is_slippery=True)
n_states = env.observation_space.n
n_actions = env.action_space.n



In [3]:
# -------------------------------------------------
# Value Iteration Algorithm
# -------------------------------------------------

def value_iteration(env, gamma=0.99, theta=1e-8):
    """
    Performs value iteration and returns the optimal value function.
    """

    n_states = env.observation_space.n
    n_actions = env.action_space.n

    V = np.zeros(n_states)
    iteration = 0

    while True:
        delta = 0

        for s in range(n_states):

            action_values = np.zeros(n_actions)

            for a in range(n_actions):

                for prob, next_state, reward, done in env.unwrapped.P[s][a]:
                    action_values[a] += prob * (
                        reward + gamma * V[next_state] * (not done)
                    )

            best_value = np.max(action_values)

            delta = max(delta, abs(best_value - V[s]))
            V[s] = best_value

        iteration += 1

        if delta < theta:
            break

    # Extract Optimal Policy
    policy = np.zeros(n_states, dtype=int)

    for s in range(n_states):

        action_values = np.zeros(n_actions)

        for a in range(n_actions):
            for prob, next_state, reward, done in env.unwrapped.P[s][a]:
                action_values[a] += prob * (
                    reward + gamma * V[next_state] * (not done)
                )

        policy[s] = np.argmax(action_values)

    return V, policy, iteration


In [4]:
# -------------------------------------------------
# Run Value Iteration
# -------------------------------------------------

V, policy, iterations = value_iteration(env)


In [5]:

# -------------------------------------------------
# Display Output
# -------------------------------------------------
print("Name : Sanjay Sivaramakrishnan M")
print("Register Number : 212223240151")
print("Value Iteration Completed")
print("Number of Iterations:", iterations)

print("\nOptimal State-Value Function:")
print(np.round(V.reshape(4, 4), 4))
action_symbols = {
    0: "L",
    1: "D",
    2: "R",
    3: "U"
}

policy_grid = np.array(
    [action_symbols[action] for action in policy]
).reshape(4, 4)

print("\nOptimal Policy:")
print(policy_grid)

env.close()




Name : Sanjay Sivaramakrishnan M
Register Number : 212223240151
Value Iteration Completed
Number of Iterations: 175

Optimal State-Value Function:
[[0.7474 0.7587 0.793  0.8514]
 [0.7587 0.5007 0.     0.8772]
 [0.793  0.     0.6135 0.9296]
 [0.8514 0.8772 0.9296 0.    ]]

Optimal Policy:
[['D' 'U' 'U' 'R']
 ['L' 'L' 'L' 'R']
 ['L' 'L' 'D' 'R']
 ['D' 'D' 'D' 'L']]
